development:
  adapter: postgresql
  encoding: unicode
  database: pushcart_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: pushcart_test
  pool: 5
  username:
  password:

staging:
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.application.secrets.db_name %>
  pool: 10
  username: <%= Rails.application.secrets.db_user %>
  password: <%= Rails.application.secrets.db_password %>

production:
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.application.secrets.db_name %>
  pool: 10
  username: <%= Rails.application.secrets.db_user %>
  password: <%= Rails.application.secrets.db_password %>
  host: <%= Rails.application.secrets.db_host %>